### ISSUE TITLE
Netlify deploy preview points to production CSS

### ISSUE THREAD

**Issue by metbril** [janraasch/hugo-scroll#14]
I am trying to build my site with Netlify. I want to make sure everything is working fine, before I release it.

In local builds, the CSS is fetched relative from the server root. But when I look at the deploy preview, it's CSS is pointing to the absolute path from the `baseURL`. Instead, it should be relative in this case to make it work.

https://github.com/janraasch/hugo-scroll/blob/9a99a8fb3afa167cd3ac66bc58c14069f5a848d2/layouts/partials/head.html#L22

repo: https://gitlab.com/metbril/home2020/

netlify deploy preview: https://stupefied-mcclintock-1d5947.netlify.app/

generated html:

```
<link rel="stylesheet" href="https://robertvanbregt.nl/css/screen.css">
```

**Comment by janraasch** [comment]
Hi @metbril, thank you for getting in touch 🙏.

Looking at https://www.robertvanbregt.nl/, it seems like you already made it passed the initial release 👍 🎉. Very nice. Congratulations and I am sorry I could not reply earlier.

**To your question:**

It looks like you did not specify the `baseURL` in your »deploy preview« build script on netlify. This can be done using the `DEPLOY_PRIME_URL`-environment-variable. 

E.g. you could add a `netlify.toml`-file to the base of your project with the following content:

```toml
[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.78.2"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
```

Check out https://github.com/janraasch/hugo-product-launch/blob/master/exampleSite/netlify.toml for a working example of this on another project of mine.

I hope that helps 🤓.  

Of course, let me know, if you have any follow-up questions.

Have a good week 👋,
Jan
