### ISSUE TITLE
CSS Syntax error

### ISSUE THREAD

**Issue by susnux** [janraasch/hugo-scroll#68]
The current CSS has a syntax error:

https://github.com/janraasch/hugo-scroll/blob/1d92c6b79b97577f48cb88d28c08f7bc75ccb000/static/css/screen.css#L417-L422

This is not valid CSS nesting (which is not supported by any browser anyway).

Should probably changed to this:
```css
table.plain tbody > tr:nth-child(odd) > td,
table.plain tbody > tr:nth-child(odd) > th {
    background: transparent;
}
```
